### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by jeromeku** [Bruce-Lee-LY/flash_attention_inference#1]
Getting this error when running `build.sh` for a `Debug` build with architecture set to `86` on an A6000 with `nvcc` 11.8:
```
CMake Error at flash_attention_inference_generated_flash_fwd_hdim256_fp16_sm80.cu.o.Debug.cmake:280 (message):
  Error generating file
  /notebooks/flash_attention_inference/build/CMakeFiles/flash_attention_inference.dir/src/flash_attn_v2/./flash_attention_inference_generated_flash_fwd_hdim256_fp16_sm80.cu.o
 ```
This occurs for every `hdim >= 96`.

I'm able to run `build.sh` with the above settings if I remove all `hdim` specializations above 64 for flash attention v2 (simply deleting these files).  However, when I try to run the executable with `batch size = 1`, `head dim = 32`,` num heads Q = 1`, `num head K = 1,` `seq len = 64`, I get:
```
[FAI 2023-09-22 23:31:32 34890:34890 flash_fwd_launch_template.h:44 operator()] CUDA Runtime API error = 0002 "cudaErrorMemoryAllocation", runtime version: 11080, driver version: 12000
```

This occurs after `flash attention` profiling is run successfully but as soon as `flash attention v2` kernel launches.

**Comment by Bruce-Lee-LY** [comment]
It has been fixed.
