### ISSUE TITLE
What is Decoding Attention?

### ISSUE THREAD

**Issue by Nick-infinity** [Bruce-Lee-LY/flash_attention_inference#2]
Hello @Bruce-Lee-LY . Can you please provide a reference to decoding attention? I am not able to find how decoding attention works.

Also, do we have any opencl implementation of all these attentions in your repo?

**Comment by Bruce-Lee-LY** [comment]
Decoding attention is specially optimized for multi head attention (MHA) using CUDA core for the decoding stage of LLM inference. It mainly refers to OpenPPL and Flash Attention, which can solve the problem of low tensor core utilization of Flash Attention in the decoding stage of LLM inference and support more types of attention and quantization optimization.

In most LLM inference decoding scenarios, the performance of Decoding Attention is better than Flash Attention and Flash Attention v2. In addition, Decoding Attention also supports GQA / MQA and ALiBi inference scenarios.

At the same time, various quantization methods were explored for KV cache in Decoding Attention, which can save nearly half of the GPU memory and reduce the cost of LLM inference.

You can refer to main.cu. There is currently no implementation of opencl.
